version: "3.5"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: zerotier_1
      APP_PORT: 3001
    
  server:
    image: zerotier/zerotier:latest
    user: "1000:1000"
    init: true
  restart: unless-stoped
